name: api-action
on: [push]
jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - run: ls
      - name: just a test
        uses: actions/checkout@v4
        
      - name: Remove old container and image
        run: |
          docker stop api-action
          docker rm api-action
          docker rmi api-action

      - name: Build Docker image
        run: docker build -t api-action .

      - name: Run Docker container in detached mode
        run: docker run -p 5000:5000 -d --name api-action api-action
